package com.darkcom.decoration.mapper;

import com.darkcom.decoration.model.Comment;
import org.apache.ibatis.annotations.Mapper;

/**
 * @author yaojy
 */
@Mapper
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMMENT
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMMENT
     *
     * @mbg.generated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMMENT
     *
     * @mbg.generated
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMMENT
     *
     * @mbg.generated
     */
    Comment selectByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMMENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_COMMENT
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Comment record);
}