package com.darkcom.decoration.mapper;

import com.darkcom.decoration.model.SmsRecord;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * @author yaojy
 */
@Mapper
public interface SmsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbg.generated
     */
    int insert(SmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbg.generated
     */
    int insertSelective(SmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbg.generated
     */
    SmsRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_SMS_RECORD
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsRecord record);

    /**
     * 校验验证码
     *
     * @param phone
     * @param verifyCode
     * @return
     */
    SmsRecord checkVerifyCode(@Param("phone") String phone, @Param("verifyCode") String verifyCode);
}