package com.darkcom.decoration.mapper;

import com.darkcom.decoration.model.UserRole;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbg.generated
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_role
     *
     * @mbg.generated
     */
    int insertSelective(UserRole record);
}