package com.darkcom.decoration.mapper;

import com.darkcom.decoration.model.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;

/**
 * @author yaojy
 */
@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TBL_USER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据手机号和密码查询用户，用于登录用户校验
     */
    User selectByPhoneAndPwd(@Param("phone") String phone, @Param("password") String password);

    /**
     * 更新用户最后登录时间
     *
     * @param userId
     * @param lastLoginTime
     */
    void updateLastLoginTime(@Param("userId") Long userId, @Param("lastLoginTime") Date lastLoginTime);

    /**
     * 根据用户名查询用户信息
     * @param username
     * @return
     */
    User getUserInfoByUserName(@Param("userName") String username);
}