package com.darkcom.decoration.model;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COMMENT.COMMENT_ID
     *
     * @mbg.generated
     */
    private Long commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COMMENT.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COMMENT.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COMMENT.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COMMENT.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_COMMENT.COMMENT_ID
     *
     * @return the value of TBL_COMMENT.COMMENT_ID
     * @mbg.generated
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_COMMENT.COMMENT_ID
     *
     * @param commentId the value for TBL_COMMENT.COMMENT_ID
     * @mbg.generated
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_COMMENT.USER_ID
     *
     * @return the value of TBL_COMMENT.USER_ID
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_COMMENT.USER_ID
     *
     * @param userId the value for TBL_COMMENT.USER_ID
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_COMMENT.CONTENT
     *
     * @return the value of TBL_COMMENT.CONTENT
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_COMMENT.CONTENT
     *
     * @param content the value for TBL_COMMENT.CONTENT
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_COMMENT.CREATE_TIME
     *
     * @return the value of TBL_COMMENT.CREATE_TIME
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_COMMENT.CREATE_TIME
     *
     * @param createTime the value for TBL_COMMENT.CREATE_TIME
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_COMMENT.UPDATE_TIME
     *
     * @return the value of TBL_COMMENT.UPDATE_TIME
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_COMMENT.UPDATE_TIME
     *
     * @param updateTime the value for TBL_COMMENT.UPDATE_TIME
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}