package com.darkcom.decoration.model;

import java.util.Date;

public class SmsRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.verifycode
     *
     * @mbg.generated
     */
    private String verifycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_SMS_RECORD.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    private Integer codeType;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.id
     *
     * @return the value of TBL_SMS_RECORD.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.id
     *
     * @param id the value for TBL_SMS_RECORD.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.phone
     *
     * @return the value of TBL_SMS_RECORD.phone
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.phone
     *
     * @param phone the value for TBL_SMS_RECORD.phone
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.verifycode
     *
     * @return the value of TBL_SMS_RECORD.verifycode
     * @mbg.generated
     */
    public String getVerifycode() {
        return verifycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.verifycode
     *
     * @param verifycode the value for TBL_SMS_RECORD.verifycode
     * @mbg.generated
     */
    public void setVerifycode(String verifycode) {
        this.verifycode = verifycode == null ? null : verifycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TBL_SMS_RECORD.create_time
     *
     * @return the value of TBL_SMS_RECORD.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TBL_SMS_RECORD.create_time
     *
     * @param createTime the value for TBL_SMS_RECORD.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Integer getCodeType() {
        return codeType;
    }

    public void setCodeType(Integer codeType) {
        this.codeType = codeType;
    }
}